meta:
  run-mode: debug
  port: 3344
  log-path: ./logs/
  log-name: console
  def-page-size: 20
  max-page-size: 50

mysql:
  host: 127.0.0.1
  port: 3306
  name: db_vid
  charset: utf8
  user: root
  password: 123
  max-idle: 10
  max-active: 100
  max-lifetime: 3600 # second

redis:
  host: 127.0.0.1
  port: 6379
  db: 1
  password: 123
  connect-timeout: 5000 # microsecond
  read-timeout: 5000 # microsecond
  write-timeout: 5000 # microsecond
  max-idle: 10
  max-active: 100
  max-lifetime: 3600 # second
  idle-timeout: 300 # second

email:
  name: xxx@yyy.zzz
  smtp-host: smtp.yyy.zzz
  smtp-port: 465
  username: xxx@yyy.zzz
  password: xxx
  expire: 3600 # second

jwt:
  secret: xxx
  issuer: vid.srv.auth
  expire: 604800 # second

casbin:
  config-path: ./rbac-model.conf
