meta:
  run-mode: debug
  port: 3344
  log-path: ./log/console.log
  def-page-size: 10
  max-page-size: 30

file:
  image-path: ./usr/image/
  image-max-size: 2 # MB
  image-url-prefix: http://localhost:3344/v1/raw/image/

mysql:
  host: 127.0.0.1
  port: 3306
  name: db_vid
  charset: utf8
  user: root
  password: 123
  log: true

redis:
  conn-type: tcp
  host: 127.0.0.1
  port: 6379
  db: 1
  password: 123
  connect-timeout: 1000 # microsecond
  read-timeout: 1000
  write-timeout: 1000

jwt:
  secret: xxx
  issuer: vid.srv.auth
  expire: 604800 # second
  redis-fmt: vid-token-%s-%s

casbin:
  config-path: ./rbac-model.conf
