run-mode: debug

meta:
  port: 3344

file:
  image-path: ./usr/image/
  image-max-size: 2 # MB
  image-url-prefix: http://localhost:3344/v1/raw/image/

mysql:
  host: 127.0.0.1
  port: 3306
  name: db_vid
  charset: utf8
  user: root
  password: 123
  log: true
  page-size: 10

redis:
  conn-type: tcp
  host: 127.0.0.1
  port: 6379
  db: 1
  password: 123
  connect-timeout: 1000 # microsecond
  read-timeout: 1000
  write-timeout: 1000

jwt:
  secret: 9C27D0C7C04BDA8A1F1B099CF4F9B1956AF5164F
  expire: 604800 # second
  issuer: vid.srv.auth
  redis-fmt: vid-token-%s-%s

search:
  dictionary-path: ./src/common/seg/dictionary.txt
